import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeLayer from "@/components/ThemeLayer";
import {Providers} from '../reduxts/provider'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ThemeLayer>
        <Providers>
        {children}
        </Providers>
       
        <ToastContainer
        position="top-center"
        autoClose={1000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        pauseOnFocusLoss
        draggable
      />
        </ThemeLayer>
      </body>
    </html>
  );
}
